// AUTO-GENERATED FILE.
// Do not edit manually. Generated by scripts/generate-games-manifest.mjs

export const games = [
  {
    "slug": "_template",
    "title": "_template",
    "href": "/games/_template/index.html",
    "thumbnail": "/images/game-placeholder.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "brick-blaster",
    "title": "Brick Blaster",
    "href": "/games/brick-blaster/index.html",
    "thumbnail": "/images/game-placeholder.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "bubble-pop-arena",
    "title": "Bubble Pop Arena",
    "href": "/games/bubble-pop-arena/index.html",
    "thumbnail": "/images/game-placeholder.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "city-quest-rise-of-the-guardian",
    "title": "City Quest Rise Of The Guardian",
    "href": "/games/city-quest-rise-of-the-guardian/index.html",
    "thumbnail": "/games/city-quest-rise-of-the-guardian/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "climate-rescue-quest",
    "title": "Climate Rescue Quest",
    "href": "/games/climate-rescue-quest/index.html",
    "thumbnail": "/games/climate-rescue-quest/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "cyber-shield-academy",
    "title": "Cyber Shield Academy",
    "href": "/games/cyber-shield-academy/index.html",
    "thumbnail": "/games/cyber-shield-academy/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "fruit-slice",
    "title": "Fruit Slice",
    "href": "/games/fruit-slice/index.html",
    "thumbnail": "/games/fruit-slice/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "kasi-quest",
    "title": "Kasi Quest",
    "href": "/games/kasi-quest/index.html",
    "thumbnail": "/games/kasi-quest/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "map-master-africa",
    "title": "Map Master Africa",
    "href": "/games/map-master-africa/index.html",
    "thumbnail": "/games/map-master-africa/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "math-sprint-arena",
    "title": "Math Sprint Arena",
    "href": "/games/math-sprint-arena/index.html",
    "thumbnail": "/games/math-sprint-arena/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "neon-hover-runner",
    "title": "Neon Hover Runner",
    "href": "/games/neon-hover-runner/index.html",
    "thumbnail": "/games/neon-hover-runner/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "neon-orb-defender",
    "title": "Neon Orb Defender",
    "href": "/games/neon-orb-defender/index.html",
    "thumbnail": "/games/neon-orb-defender/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "physics-force-lab",
    "title": "Physics Force Lab",
    "href": "/games/physics-force-lab/index.html",
    "thumbnail": "/games/physics-force-lab/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "recycle-rush",
    "title": "Recycle Rush",
    "href": "/games/recycle-rush/index.html",
    "thumbnail": "/games/recycle-rush/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "science-lab-dash",
    "title": "Science Lab Dash",
    "href": "/games/science-lab-dash/index.html",
    "thumbnail": "/games/science-lab-dash/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "space-dodger",
    "title": "Space Dodger",
    "href": "/games/space-dodger/index.html",
    "thumbnail": "/games/space-dodger/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "stack-tower",
    "title": "Stack Tower",
    "href": "/games/stack-tower/index.html",
    "thumbnail": "/games/stack-tower/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "swipe-racer",
    "title": "Swipe Racer",
    "href": "/games/swipe-racer/index.html",
    "thumbnail": "/games/swipe-racer/thumb.png",
    "category": "Arcade",
    "isPublished": true
  },
  {
    "slug": "word-dash",
    "title": "Word Dash",
    "href": "/games/word-dash/index.html",
    "thumbnail": "/games/word-dash/thumb.png",
    "category": "Arcade",
    "isPublished": true
  }
] as const;

export type Game = (typeof games)[number];
